name: check secret

on:
  push:
    branches:
      - main
  
jobs:
  check-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: check_secret_step
        env:
          MY_FIRST_SECRET_NAME_ENV: ${{ secrets.MY_FIRST_SECRET_NAME }}
        run: echo "Il mio primo segreto $MY_FIRST_SECRET_NAME_ENV"